"""
Скрипт для создания workflow файла с правильной кодировкой UTF-8
"""

import os
from pathlib import Path

def create_workflow_file():
    """Создает workflow файл с правильной кодировкой"""
    workflow_content = """name: Create Release Artifacts

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v1.0-article'
        type: string

env:
  PYTHON_VERSION: '3.10'
  ARTIFACT_NAME: 'research-artifacts'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: \${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Validate configurations
      run: |
        echo "Validating configuration files..."
        python -c "
        import yaml
        from pathlib import Path
        configs = ['configs/experiment_config.yaml', 'configs/model_svm.yml', 'configs/model_logreg.yml', 'configs/model_lstm.yml']
        for config_path in configs:
            if Path(config_path).exists():
                with open(config_path, 'r', encoding='utf-8') as f:
                    yaml.safe_load(f)
                print(f'VALID: {config_path}')
            else:
                print(f'MISSING: {config_path}')
        "

  run-experiments:
    name: Run Experiments
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: \${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Create demo results
      run: |
        python -c "
        import pandas as pd
        from pathlib import Path
        Path('results').mkdir(exist_ok=True)
        results = []
        for dataset in ['rusentiment', 'rureviews', 'taiga_social']:
            for model in ['bow_logreg', 'tfidf_svm']:
                results.append({
                    'dataset': dataset,
                    'model': model,
                    'accuracy': 0.8,
                    'f1_macro': 0.79
                })
        pd.DataFrame(results).to_csv('results/demo_results.csv', index=False)
        print('Demo results created')
        "

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-and-test, run-experiments]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: \${{ env.PYTHON_VERSION }}
    
    - name: Prepare artifacts
      run: |
        mkdir -p artifacts/{results,configs}
        cp configs/*.yaml artifacts/configs/ 2>/dev/null || true
        cp results/*.csv artifacts/results/ 2>/dev/null || true
        echo '# Research Artifacts' > artifacts/README.md
        echo 'Automatically generated' >> artifacts/README.md
    
    - name: Create ZIP
      run: |
        cd artifacts
        zip -r ../\${{ env.ARTIFACT_NAME }}-\${{ github.ref_name }}.zip .
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: \${{ env.ARTIFACT_NAME }}-\${{ github.ref_name }}.zip
        name: Release \${{ github.ref_name }}
        body: |
          Research artifacts automatically generated by GitHub Actions.
      env:
        GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
"""
    
    # Создаем папку если не существует
    Path(".github/workflows").mkdir(parents=True, exist_ok=True)
    
    # Сохраняем файл с кодировкой UTF-8
    with open(".github/workflows/release.yml", "w", encoding="utf-8") as f:
        f.write(workflow_content)
    
    print(" Workflow файл создан с кодировкой UTF-8")

if __name__ == "__main__":
    create_workflow_file()